CREATE TABLE IF NOT EXISTS `tenant` (
    `uuid` VARCHAR(31) NOT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `phone` VARCHAR(50) DEFAULT NULL,
    `name` VARCHAR(255) DEFAULT NULL
    ) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;