server:
  port: 8084



protocol:
  rate:
    limits:
      device:
        config: 100:1,300:10
      tenant:
        config: 100:1,300:10
      enabled: true
  mqtt:
    max_payload_size: 65535
    bind_address: 0.0.0.0
    bind_port: 1883
    boss_group_thread_count: 1
    worker_group_thread_count: 12

logging:
  config: classpath:logback.xml
