server:
  port: 8083

filters:
  traceId: true
  jwt: false

js:
  executor:
    threadpools: 50
  js-invoker:
    use-sandbox: true
    threadpools: 4
    max-cpu-time: 100
    max-errors: 3


mybatis-plus:
  mapper-locations: classpath*:com/ruyuan/jiangzh/iot/rule/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:???ID??   1:????id  2:????id(IdWorker)  3:????ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruyuan_iot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: Jiangzh_292679
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
